project_name: td

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{.ProjectName}}"
    dir: ./
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -s -w -X main.commit={{.ShortCommit}}
      - -s -w -X main.date={{.CommitDate}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7

release:
  github:
    owner: mchmarny
    name: td
  prerelease: auto

archives:
  - format: binary
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

checksum:
  name_template: "checksums-sha256.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - readme
      - typo

